### ISSUE TITLE
parametrer le texte à lire

### ISSUE THREAD

**Issue by KaptainJP** [Aymkdn/assistant-notifier#1]
Bonjour,
Existe-t-il une solution pour paramétrer le texte à lire et ne pas avoir une valeur en dur définie lors de la création de la notification?
exemple
texte_à_lire = réponse d'un Web Service
notifier_{{texte_à_lire}}

Le besoin serait le suivant 
"OK Google où en est on du traitement ?"
texte_à_lire = réponse("http://xxxxxxxx/")
notifier_{{texte_à_lire}}
"le traitement est en cours depuis 10 minutes"

"OK Google où en est on du traitement ?"
texte_à_lire = réponse("http://xxxxxxxx/")
notifier_{{texte_à_lire}}
"le traitement s'est terminé avec succès à 12h 15"

**Comment by Aymkdn** [comment]
Je vois 2 possibilités : 

1. Soit tu crées [un plugin](https://github.com/Aymkdn/assistant-template) qui gère ta tâche et quand c'est fini va notifier Google (en faisant appel au plugin *notifier*)... si ton appel au Web Service est déjà codé en JavaScript ça peut être facile à intégrer
2. Soit tu crées un [WebHook sur IFTTT](https://ifttt.com/maker_webhooks) et tu fais un POST vers ce WebHook qui contiendra la phrase que tu veux faire dire. Le WebHook transmet alors le paramètre envoyé en POST à Pushbullet qui transmet ensuite à *notifier*

**Comment by KaptainJP** [comment]
J'ai fais un amalgame des plugins existant et cela donnerait cela. Qu'en penses tu? 

/** 
* le principe de ce plugins est d'aller chercher un texte à lire en retour d'un WS défini dans le fichier de config 
* ce WS retourne un body json contenant 2 rubriques : Erreur et ReponseALire 
* Si Erreur est > 0 => pas de texte à lire 
* Si Erreur = 0 => lecture du texte contenu dans ReponseALire 
* 
* 
* "plugins": { 
* "Lecture": { 
* "url":"http://www.truc.fr/webservice/trucalire.php" 
* } 
* } 
* 
* le retour json du WS 
* { 
* "Erreur":0, 
* "ReponseALire":"Ceci est le texte qui sera lu par Google Home" 
* } 
* 
* 
*/ 

var request = require('request-promise-native'); 

/** 
* on crée une fonction `AssistantLecture` 
* @param {Object} configuration L'objet `configuration` qui vient du fichier configuration.json 
*/ 
var AssistantLecture = function(configuration) { 
this.url = configuration.url; 
} 

/** 
* Init le plugin 
* 
* @param {Object} plugins Un objet représentant les autres plugins chargés 
* @return {Promise} 
*/ 
AssistantLecture.prototype.init = function(plugins) { 
this.plugins = plugins; 
return Promise.resolve(this); 
}; 

/** 
* Fonction appelée par le système central 
* 
* @param {String} commande La commande envoyée depuis IFTTT par Pushbullet 
* @return {Promise} 
*/ 
AssistantLecture.prototype.action = function(commande) { 
// la commande va ressembler à http://www.truc.fr/webservice/trucalire.php 
var _this=this; 
commande = '"'+commande.replace(/'/g,'\\"').replace(/, /g,",")+'"'; 
commande = JSON.parse(commande); 
if (typeof commande==="string") commande = JSON.parse(commande); 
return request({ 
'url' : _this.url }) 
.then(function(response){ 
if (response) { 
var body = JSON.parse(response); 
var lerc = body.Erreur; 
if (lerc > 0) return _this.plugins.notifier.action("Je n'ai pas d'information pour le moment"); 
else { 
var speak = body.ReponseALire; 
if (_this.plugins.notifier) return _this.plugins.notifier.action(speak); 
else { 
console.log("[Assistant-Lecture] ATTENTION: Le plugin 'notifier' n'a pas été installé... le résultat de cette action ne peut donc pas être diffusé sur un appareil et sera seulement inscrit dans cette fenêtre."); 
} 
console.log("[Assistant-Lecture] "+speak); 
} 
console.log("[Assistant-Lecture] erreur WS : "+lerc); 
} else { 
console.log("[Assistant-Lecture] Erreur lors de l'accès à la ressource..."); 
if (_this.plugins.notifier) return _this.plugins.notifier.action("L'action a échoué..."); 
} 
}) 
.catch(function(err) { 
console.log("[Assistant-Lecture] Erreur => ",err) 
}) 
}; 

/** 
* Initialisation du plugin 
* 
* @param {Object} configuration La configuration 
* @param {Object} plugins Un objet qui contient tous les plugins chargés 
* @return {Promise} resolve(this) 
*/ 
exports.init=function(configuration, plugins) { 
return new AssistantLecture(configuration).init(plugins) 
.then(function(resource) { 
console.log("[Assistant-Lecture] Plugin chargé et prêt."); 
return resource; 
}) 
} 

----- Mail original -----

De: "Aymeric" <notifications@github.com> 
À: "Aymkdn/assistant-notifier" <assistant-notifier@noreply.github.com> 
Cc: "KaptainJP" <jp.damas@free.fr>, "Author" <author@noreply.github.com> 
Envoyé: Lundi 19 Février 2018 17:51:49 
Objet: Re: [Aymkdn/assistant-notifier] parametrer le texte à lire (#1) 


Je vois 2 possibilités : 

    1. Soit tu crées un plugin qui gère ta tâche et quand c'est fini va notifier Google (en faisant appel au plugin notifier )... si ton appel au Web Service est déjà codé en JavaScript ça peut être facile à intégrer 
    2. Soit tu crées un WebHook sur IFTTT et tu fais un POST vers ce WebHook qui contiendra la phrase que tu veux faire dire. Le WebHook transmet alors le paramètre envoyé en POST à Pushbullet qui transmet ensuite à notifier

**Comment by Aymkdn** [comment]
Utilise plutôt l'interface de Github (https://github.com/Aymkdn/assistant-notifier/issues/1) pour répondre plutôt que de répondre par email ^^ 

Oui ça doit pouvoir le faire. Par contre je n'ajouterai pas ce plugin au "store" car je n'en vois pas l'intérêt à vrai dire...
Si tu veux l'utiliser, tu peux l'ajouter à ton Github avec le nom **assistant-lecture** puis dans ton répertoire `assistant-plugins` pour l'installer tu fais : 
```
npm install git+https://github.com/KaptainJP/assistant-lecture.git
```

Ensuite tu peux faire des modifications directement dans le dossier `node_modules/assistant-lecture/` pour continuer tes tests et quand t'es bon tu modifies sur la version en ligne de Github.

Si tu ne veux pas le mettre en ligne, tu peux aussi faire un `npm install` avec un dossier en local sur ton ordinateur directement (mais ça merdouille des fois).

**Comment by KaptainJP** [comment]
Je suis un peu beaucoup très énormément bleu sur github
J'ai réussi tant bien que mal à faire des gists sur github mais je ne sais pas comment générer un .git. Alors j'ai tenté l'installation depuis un répertoire local mais j'ai des erreurs là aussi... tu connaîtrais pas un tuto pour débutants ?

**Comment by Aymkdn** [comment]
Non.... Demande à Google ^^

**Comment by KaptainJP** [comment]
OK, j'ai trouvé une vidéo en français. C'est mieux qu'un long texte en anglais... Installation OK mais 1er essai KO : index> <node:1088> UnhandledPromiseRejectionWarning: Unhandled promise rejection <rejection id : 6>:SyntaxError: Unexpected end of JSON input. 

J'ai fait plusieurs essais sur la config d'appel du push lecture_, ou lecture_rien ou lecture et cela semble faire varier l'id de rejet. y a-t-il un formalisme que j'aurais oublié d'intégrer?

**Comment by Aymkdn** [comment]
Regarde ce que tu as dans `response` car l'erreur semble liée au parse de la réponse.

**Comment by KaptainJP** [comment]
ça y est. cela fonctionne et c'est opérationnel. Pour info, mon problème était que je cherchais à passer une variable à l'appel de l'action alors que je n'avais rien à lui passer. J'ai supprimé le code correspondant à cette variable "commande".
Mon utilisation de base de ce plugin va être de gérer mes parties de tarots avec les copains avec Google Home. J'ai créé des webhooks pour alimenter une base de données mysql au fur et à mesure de la soirée et j'appelle "lecture" pour avoir un point de situation de la partie "Après 5 parties, Denis premier avec 240 points, Fred deuxième avec 120 points, Hubert troisième avec 20 points, Jean Philippe quatrième avec -120 points, Patrice dernier avec -300 points".
Une utilisation de ce plugin est d'avoir des informations sur quelque chose que l'on veut suivre : les résultats du WE d'un club de sport depuis son site internet, des infos locales d'une commune etc...

Il suffit juste de paramétrer dans configuration.json le site à suivre

Une version future pourrait permettre de suivre plusieurs sites via le textfield de Google.

Merci beaucoup pour ton aide.

**Comment by Aymkdn** [comment]
OK cool ! Du coup, je ferme l'issue 😊

Content de voir ce que les gens arrivent à créer avec ça !

**Comment by KaptainJP** [comment]
NB : si un jour tu veux l'intégrer à Assistant-Plugins, y a pas de soucis.

**Comment by Aymkdn** [comment]
Donne moi l'URL de ton Github et je regarderai ça de plus près !

**Comment by Aymkdn** [comment]
Alors, ce qui me gène, pour le diffuser à tout le monde, c'est qu'il est vraiment spécifique à tes besoins, puisque tu attends un retour JSON avec "Error" et "ReponseALire"... Du coup, à part le webservice que tu as créé, il ne peut s'appliquer à personne d'autre !

**Comment by jth62** [comment]
Bonjour à tous,
J'ai un problème à peu prêt similaire je pense, 
j'ai installer Assistant-Plugins sur mon rasberry dans le but d'envoyer à mon google home des notifications audio depuis Domoticz.
Je passe donc une requête Webhooks dans iftt, malheureusement j'obtient le message d'erreur ci dessous : 
[assistant] Assistant v2.0.12 : Chargement en cours...
[assistant] 1 plugin trouvé.
[assistant] Chargement du plugin 'notifier' (v2.1.6)
[assistant-notifier] Plugin chargé et prêt.
[assistant] Connexion au flux de PushBullet...
[assistant] (2019-02-19 16:26:41) Connecté ! Prêt à exécuter les ordres.
[assistant] (2019-02-19 16:26:48) Commande reçue:  [ 'notifier_{host} \'ceci est un test\'' ]
[assistant] (2019-02-19 16:26:48) Appel du plugin 'notifier'
[assistant-notifier] (host) Lecture du message : 'ceci est un test'
(node:8647) UnhandledPromiseRejectionWarning: TypeError: "port" option should be a number or string: function (err, result) {
      if (err) rej(err);
      else res(result);
    }
    at lookupAndConnect (net.js:1060:13)
    at TLSSocket.Socket.connect (net.js:1037:5)
    at Object.exports.connect (_tls_wrap.js:1077:12)
    at Client.connect (/home/pi/assistant-plugins/node_modules/assistant-notifier/node_modules/castv2-client/node_modules/castv2/lib/client.js:35:21)
    at PlatformSender.connect (/home/pi/assistant-plugins/node_modules/assistant-notifier/node_modules/castv2-client/lib/senders/platform.js:27:15)
    at /home/pi/assistant-plugins/node_modules/assistant-notifier/notifier.js:33:13
    at new Promise (<anonymous>)
    at AssistantNotifier.prom (/home/pi/assistant-plugins/node_modules/assistant-notifier/notifier.js:28:10)
    at /home/pi/assistant-plugins/node_modules/assistant-notifier/notifier.js:78:15
    at Array.forEach (<anonymous>)
(node:8647) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:8647) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Je ne comprend pas vraiment d'ou vient le problème, quelqu'un pourrait il m'aider svp ? 
Merci d'avance, 
Julien

**Comment by Aymkdn** [comment]
@jth62 j'ai déplacé ton issue là : https://github.com/Aymkdn/assistant-plugins/issues/230
