### ISSUE TITLE
Plantage quand erreur de connexion

### ISSUE THREAD

**Issue by fjouault** [Aymkdn/assistant-notifier#11]
Bonjour,

Les erreurs de connexion ne sont pas catchées et causent du coup un plantage de l'application.

Le patch suivant log l'erreur mais ne fait rien de plus. Il faudrait idéalement détecter où on en est et remettre le système dans le bon état (e.g., remettre le volume d'origine si on l'avait changé avant l'erreur), mais on évite déjà le plantage.

```
--- a/notifier.js
+++ b/notifier.js
       gh.forEach(function(host) {
         var client = new Client();
         currentVolume[host] = -1;
+        client.on('error', function(err) {
+          console.log('[assistant-notifier] %s', err)
+        });
         _this.prom(client, 'connect', host)
         .then(function() {
           if (_this.volume > -1 && defaultNotification) {
```

**Comment by Aymkdn** [comment]
Salut,

Merci pour ça ! J'ai juste rajouté ton bout de code… Pour le changement du volume, il faudrait en effet le remettre à l'état d'origine, mais du coup il faudrait réouvrir une connexion etc… Comme je n'utilise pas de média long, ça n'a jamais planté. Si le plantage arrive régulièrement chez toi, tu peux toujours ajouter le code nécessaire et me faire un pull request.

J'ai mis à jour le [README](https://github.com/Aymkdn/assistant-notifier/blob/master/README.md) et j'ai publié la nouvelle version.

**Comment by fjouault** [comment]
Ok, merci. Je verrai à l'usage si d'autres modifications s'avèrent nécessaires.
