### ISSUE TITLE
Assistant Notifier

### ISSUE THREAD

**Issue by rick443** [Aymkdn/assistant-notifier#12]
Bonjour,
J'ai un problème qui se présente aléatoirement :
Quand j'appelle le plugin Notifier depuis une commande DOS (voir pièce jointe), j'ai de temps en temps un bug
![Erreur_Notifier](https://user-images.githubusercontent.com/46280404/98564487-b9b07280-22ac-11eb-8af5-86b7a7a66679.png)

Si je relance la même commande, ça passe...ou pas ....
Avez-vous une idée ?

Cdlt

**Comment by rick443** [comment]
non, cela ne change rien....

**Comment by Aymkdn** [comment]
Vérifie que tu as la bonne version. Car c'est sûr que tu as le même problème. Du coup, je ne peux rien de plus pour toi et je t'invite à poursuivre sur https://github.com/zlargon/google-tts/issues/33

Sinon, tu peux utiliser la voix d'IBM ou Google Text-to-speech (au lieu de celle par défaut) qui évitera ce problème, voir la doc pour savoir comment faire : https://aymkdn.github.io/assistant-plugins/?plugin=notifier

**Comment by rick443** [comment]
j'ai executé la commande npm update google-tts-api
le fenetre DOS me redonne la amin (sans erreur)
qd je vérifie le fichier D:\Assistant_Vocal\assistant-plugins\node_modules\google-tts-api\package.json, je vois:
  "_from": "google-tts-api@0.0.4",
  "_id": "google-tts-api@0.0.4",
  "_inBundle": false,

La mise à jour ne fonctionne pas visiblement, car visiblement elle dedvrait être en 0.0.5

Merci pour votre aide
