### ISSUE TITLE
Notifier

### ISSUE THREAD

**Issue by rick443** [Aymkdn/assistant-notifier#13]
j'ai executé la commande npm update google-tts-api
le fenêtre DOS me redonne la main(sans erreur)
qd je vérifie le fichier D:\Assistant_Vocal\assistant-plugins\node_modules\google-tts-api\package.json, je vois:
"_from": "google-tts-api@0.0.4",
"_id": "google-tts-api@0.0.4",
"_inBundle": false,

La mise à jour ne fonctionne pas visiblement, car visiblement elle devrait être en 0.0.5

Merci pour votre aide

**Comment by Aymkdn** [comment]
Comme indiqué dans mon autre message, je t'invite à utiliser une autre voix https://github.com/Aymkdn/assistant-notifier/issues/12#issuecomment-724143840

Si ça te pose vraiment un problème, alors je t'aiderai pour mettre à jour le paquet....
