### ISSUE TITLE
get token key failed from google

### ISSUE THREAD

**Issue by ramet** [Aymkdn/assistant-notifier#15]
Tout d'abord merci pour ces plugins.
Depuis quelques jours, ce plugin ne permet plus de faire parler le Google Home.
L'API GoogleTTS semble avoir été modifiée : https://github.com/zlargon/google-tts/issues/36
Je vais essayer d'utiliser la voix IBM en remplacement.

**Comment by Aymkdn** [comment]
Mets à jour avec la dernière version de `assistant-notifier` qui doit embarquer une version de `google-tts` qui fonctionne ([voir cette autre issue](https://github.com/Aymkdn/assistant-notifier/issues/14)).

Sinon, en effet tu peux utiliser une autre voix.

**Comment by ramet** [comment]
Merci pour ce retour rapide. Je suspect donc un blocage de mon IP pour le service Google Translate.
Je pense avoir configuré correctement le service IBM avec le serveur Francfort et mon token.
Mais je n'obtiens pas le retour audio depuis ton service : https://assistant.kodono.info/notifier.php

**Comment by Aymkdn** [comment]
Je viens de tester et ça fonctionne chez moi. Tu as peut-être mal fait quelque chose ?

**Comment by ramet** [comment]
Autant pour moi, je me suis trompé de service, j'avais sélectionné Speech-to-text au lieu de Text-to-Speech. C'est bon pour moi. On peut fermer cette issue. Merci.

**Comment by ramet** [comment]
Pour information, le package https://github.com/ncpierson/google-translate-tts
permet de générer le fichier mp3 avec la nouvelle API Google Translate, il faut par contre produire l'URL qui héberge le fichier mp3...

**Comment by Aymkdn** [comment]
OK je regarderai ça quand j'ai un moment ! Merci

**Comment by Aymkdn** [comment]
Visiblement la v0.0.6 corrige le problème déjà : https://github.com/zlargon/google-tts/blob/master/CHANGELOG.md

Je viens de bumper cette version dans `assistant-notifier`. Une mise à jour du plugin mettra donc à jour la lib Google TTS également.

**Comment by ramet** [comment]
Oui, je confirme, merci.
