### ISSUE TITLE
mes GH ne parlent plus 

### ISSUE THREAD

**Issue by vjooris** [Aymkdn/assistant-notifier#16]
Bonjour,
Je suis un super fan de ce plugin, mais depuis quelques jours mes GH sont muets.
Je reçois bien les motifs Pushbullet.
J'ai installé Assistant-plugins que une Debian 10 avec NodeJS 8.16.2.
J'utilise la version 2.1.10 de notifier.
Voici le log de ma Debian
`root@NodeJS:/assistant-plugins# node index.js
[assistant] Assistant v2.0.13 : Chargement en cours...
[assistant] 1 plugin trouvé.
[assistant] Chargement du plugin 'notifier' (v2.1.10)
[assistant-notifier] Plugin chargé et prêt.
[assistant] Connexion au flux de PushBullet...
[assistant] (2020-12-06 13:26:54) Connecté ! Prêt à exécuter les ordres.
[assistant] (2020-12-06 13:27:12) Commande reçue:  [ 'notifier_show' ]
[assistant] (2020-12-06 13:27:12) Appel du plugin 'notifier'
[assistant-notifier] (GH_Bureau,GH_Entree) Lecture du message : show
(node:2887) UnhandledPromiseRejectionWarning: Error: get token key failed from google
    at module.exports (/assistant-plugins/node_modules/google-tts-api/lib/key.js:32:9)
    at <anonymous>
(node:2887) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2887) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.      
`

Sais-tu m'aider à l'interpréter et à refaire parler mes GH ? (je n'y connais  RIEN en linux ...)

Merci beaucoup.

Vincent

**Comment by Aymkdn** [comment]
Tu peux essayer de mettre à jour le plugin en utilisant `npm update` car la dernière mise à jour pourrait résoudre au moins en partie le problème.

Il y a un soucis avec Google Translate causant ce soucis récurrent. Tu peux configurer une autre voix pour résoudre le problème, vois la doc : https://aymkdn.github.io/assistant-plugins/?plugin=notifier

Je dois regarder aussi pour utiliser un autre module pour corriger le problème de Google : voir https://github.com/Aymkdn/assistant-notifier/issues/15

**Comment by Aymkdn** [comment]
Je viens de mettre à jour le plugin en version 2.1.11.

Je t'invite à mettre à jour : https://aymkdn.github.io/assistant-plugins/#comment-mettre-jour-

**Comment by vjooris** [comment]
Merci de ta réponse super rapide.
J'ai fait le `nom update`.
J'ai essayé avec la voix IBM.
Cà fonctionne "un peu" mieux : mon GH fait le BONG (qu'il ne faisait pas avec la voix Google) mais ne dit rien.
Voici le log de ma Debian 
`root@NodeJS:/assistant-plugins# node index.js
[assistant] Assistant v2.0.13 : Chargement en cours...
[assistant] 1 plugin trouvé.
[assistant] Chargement du plugin 'notifier' (v2.1.10)
[assistant-notifier] Plugin chargé et prêt.
[assistant] Connexion au flux de PushBullet...
[assistant] (2020-12-06 16:30:45) Connecté ! Prêt à exécuter les ordres.
[assistant] (2020-12-06 16:30:58) Commande reçue:  [ 'notifier_vois IBM' ]
[assistant] (2020-12-06 16:30:58) Appel du plugin 'notifier'
[assistant-notifier] (GH_Bureau,GH_Entree) Lecture du message : vois IBM
`
Je me demande si ce n'est pas gun problème de clé API. J'ai fait de très nombreux essais, mais sans succès : sur leur site, ils ont changés par rapport à ta doc, et celle d'IBM n'est pas bonne non plus. pfff
Je ne sais plus quoi essayer.

**Comment by Aymkdn** [comment]
Le plugin n'est pas à jour. Refais un `npm update`.

**Comment by Aymkdn** [comment]
Une fois la mise à jour faite tu pourras réutiliser la voix de Google

**Comment by Aymkdn** [comment]
Et en effet, IBM a modifié son site. Je viens de modifier [la doc](https://github.com/Aymkdn/assistant-notifier/blob/master/README.md) en conséquence.

Pour avoir la clé API : 
- va sur https://cloud.ibm.com/resources
- clique sur "Services" puis sur "Text to Speech"
- tu devrais avoir la clé API : c'est celle là qu'il faut utiliser

**Comment by vjooris** [comment]
merci, ils ont tout changé sur le site d'IBM, et j'ai finalement trouvé (mais avec ma vue merdique),où trouver la bonne API, et ça fonctionne.
Je réessaie un Nième non update

**Comment by vjooris** [comment]
Merci, nos messages se so nt croisés

**Comment by vjooris** [comment]
voici le résultat de mon nom update
`+ assistant-notifier@2.1.11
removed 2 packages, updated 2 packages and audited 131 packages in 5.585s

1 package is looking for funding
  run `npm fund` for details

found 2 high severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
root@NodeJS:/assistant-plugins# 
`

**Comment by Aymkdn** [comment]
Cette fois c'est bien la dernière version :-)

**Comment by vjooris** [comment]
et en effet, ça fonctionne !


MMEERRCCII !!!!!!!!!!!!
