### ISSUE TITLE
Pushbullet a besoin d'un compte pro 

### ISSUE THREAD

**Issue by Aymkdn** [Aymkdn/assistant-notifier#18]
Bonjour,  j'ai  une mauvaise nouvelle... ca ne fonctionne  plus...
faut avoir un compte pro sur pushbulet 😭
![Screenshot_20210216-195606_IFTTT](https://user-images.githubusercontent.com/33859641/108109818-b6d6d200-7092-11eb-92b0-9f6a85e741b5.jpg)

_Originally posted by @nusmiaf in https://github.com/Aymkdn/assistant-notifier/issues/17#issuecomment-780055678_

**Comment by Aymkdn** [comment]
Ah bon ?! Fuck... C'était le plus simple et pratique.... Faudra que je réfléchisse à une alternative et que je modifie toutes les documentations...

**Comment by nusmiaf** [comment]
cumulé avec un compte pro IFTTT  ca va faire cher   par mois  😕

**Comment by Aymkdn** [comment]
Alors, je viens de tester, et chez moi ça fonctionne. Je pense que tu as fait trop d'appels à Pushbullet ce mois-ci et que tu as [dépassé le quota](https://docs.pushbullet.com/) : 

> Free accounts (without a Pro subscription) are limited to 500 pushes per month. Going over will result in an error when sending a Push.

500 appels/mois c'est déjà pas mal (une quinzaine par jour) :-) Peut-être que tu as fait beaucoup de tests qui t'ont bouffé ton quota ? Dans la doc ils expliquent comment faire pour voir quand son quota est renouvelé.

Concernant IFTTT, il est possible de [feinter pour ne pas payer ](https://github.com/Aymkdn/assistant-plugins/issues/267#issuecomment-695797614) (mais ne pas l'ébruiter sinon ils vont sûrement bloquer cette astuce).

Je ferme cet issue du coup !

**Comment by nusmiaf** [comment]
bonjour,  vue comme  ça c'est vrais qu'avez tout les tests effectué plus le fonctionnement normalement...j'ai due en passer un paquet effectivement 🙄
