### ISSUE TITLE
mes GH ne parlent à nouveau plus

### ISSUE THREAD

**Issue by vjooris** [Aymkdn/assistant-notifier#19]
Salut,
Comme en déc 2020, mes GH sont à nouveau muets ;-(
https://github.com/Aymkdn/assistant-notifier/issues/16

Je me demande si ce n'est pas à nouveau Google qui a changé son API, car ils ne parlent plus depuis le 1 octobre.
J'ai bien les notifs sur Pushbullet, mais rien ensuite (donc ce n'est pas ma VM qui aurait un problème).

Si tu sais adater/tester chez toi ce serait super.

Merci !

**Comment by Aymkdn** [comment]
Je suis parti en vacances. Je rentre dans une semaine... 

Mais un utilisateur m'a envoyé un mail aujourd'hui me disant que depuis le 1er octobre il y a un problème de certificat avec Pushbullet.

Faudra que je regarde à mon retour si j'en apprends plus...

**Comment by vjooris** [comment]
merci et bonnes vacances

**Comment by vjooris** [comment]
depuis hier soir mes GH parlent à nouveau ;-)
sans avoir rien fiat : c'est beau l'informatique ;-)
Bonnes fin de vacances

**Comment by Aymkdn** [comment]
Ça devait être un soucis chez Pushbullet qu'ils ont dû résoudre dans le week-end 👌

**Comment by vjooris** [comment]
Salut,
Cela fait depuis le début de l'année que mes GH sont à nouveau muets.

Comme je n'ai vu aucune issue, je relance celle-ci.
Peux-tu SVP me confirmer que tout va toujours bien chez toi ?

Ce que j'ai fait 1) attendre patiemment, 2) redémarrer ma machine Linux, 3) vérifier qu'il n'y avait pas une nouvelle version du plug-in.
As-tu d'autres idées ? (J'ai IFTTT Pro et Pushbullet Pro)
Merci
Vincent

**Comment by Aymkdn** [comment]
Ça fait bien longtemps que je ne l'utilise plus...

Mais mon plugin utilise une très vieille version de https://www.npmjs.com/package/google-tts-api qu'il faudrait mettre à jour.

J'essaie de regarder ça ce week-end.

**Comment by vjooris** [comment]
ah bon tu ne n'utilise plus ?
Chez moi c'est MUST have : notifications de portes oubliées ouvertes la nuit, rappel poubelles spéciales, température piscine, ....
j'attends ton retour s'il faut mettre à jour NodeJS et/ou le code ...
Merci en tout cas

**Comment by Aymkdn** [comment]
Alors, je viens de tester chez moi en ligne de commande (`node ./node_modules/assistant-plugins/assistant-cli.js "notifier_ceci est un message de test"`) et ça fonctionne toujours…

Qu'elle est ta configuration du plugin ? Utilises-tu une voix particulière, si oui vérifier si ton compte fonctionne toujours… L'IP de ton Google Home est toujours la bonne ?

Test également en ligne de commande (donc sans passer par IFTTT/Pushbullet)

**Comment by vjooris** [comment]
Merci pour le temps passé pour les tests.
J'ai vérifié la config :
`{
  "main": {
    "pushbullet_token": "o.xxxxx"
  },
  "plugins": {
    "notifier": {
      "host": {
        "GH_Cuisine":"192.168.1.146",
        "GH_Entree":"192.168.1.148",
        "GH_Bureau":"192.168.1.149"
      }
    }
  }
}
`
les IP de mes GH sont toujours ok (normal, réservation d'IP au niveau de mon router)
j'ai renouvelé le token pushbullet au cas où et redémarré la Débian.
pas de voix particulière.
Je vois les notifs pushbullet sur mon smartphone.

Voici ce que j'ai en cligne de commande :
`Linux NodeJS 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Sat Dec  5 21:35:52 2020 from 192.168.1.10
root@NodeJS:~# node ./node_modules/assistant-plugins/assistant-cli.js "notifier_ceci est un message de test"
module.js:550
    throw err;
    ^

Error: Cannot find module '/root/node_modules/assistant-plugins/assistant-cli.js'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
root@NodeJS:~# 
`

Le plugin serait-il corrompu chez moi ? (je pourrais tenter de le ré-installer ?)
étant très loin d'être un expert, tu as peut-être d'autres idées ?

**Comment by Aymkdn** [comment]
La commande doit être tapée dans le répertoire `assistant-plugins`, là où se trouve ton fichier de configuration

**Comment by vjooris** [comment]
quelle rapidité de réponse.

Bonne et mauvaise nouvelle : ça fonctionne en ligne de commande.
`root@NodeJS:~# cd /assistant-plugins
root@NodeJS:/assistant-plugins# node ./node_modules/assistant-plugins/assistant-cli.js "notifier_ceci est un message de test"
[assistant] Chargement du plugin 'notifier' (v2.1.11)
[assistant-notifier] Plugin chargé et prêt.
[assistant] Commande reçue:  [ 'notifier_ceci est un message de test' ]
[assistant] Appel du plugin 'notifier'
[assistant-notifier] (GH_Cuisine,GH_Entree,GH_Bureau) Lecture du message : ceci est un message de test
root@NodeJS:/assistant-plugins# `

Comme je reçois une notif pushbullet, c'est que IFTTT est ok ?
Alors ce serait entre pushbullet et le plugin qu'il y aurait un soucis ?

Ton exemple dans IFTTT, tu ne l'as plus (je l'ai gardé pour faire des tests, et m'affranchir de ma box domotique)

**Comment by Aymkdn** [comment]
Viens me parler sur le tchat du site https://assistant.kodono.info/freebox/ – j'y suis là, pour qu'on voit en direct.

**Comment by vjooris** [comment]
merci, mais il faut créer un compte ? et je n'ai pas de freebox.
Sinon tu peux m'appeler par WhatsApp au +32xxxx

**Comment by Aymkdn** [comment]
Non pas de compte, ni de Freebox. Tu parles juste en cliquant sur l'icône du tchat en bas à droite :)

**Comment by Aymkdn** [comment]
Suite à notre discussion, je ne sais pas quoi te dire de plus… Je ferme ce ticket puisque tout fonctionne chez moi !

Bon courage

**Comment by vjooris** [comment]
Merci en tout cas, et je te dis dès que ok.
Bonne soirée

**Comment by vjooris** [comment]
Salut, 
Je prends (enfin) le temps de tout réinstaller (ce n'était pas un problème d'heure, car sur mon exsi il m'affichait l'heure UTC ... donc normal qu'il y ait 1 heure de décalage).
c'était laquelle encore la version de NodeJS qui fonctionnait chez toi ?
Merci

**Comment by Aymkdn** [comment]
J'ai Node v12.15.0

**Comment by vjooris** [comment]
YESSS !!! mes GH reparlent enfin.
J'ai réinstallé la v12 de JS, puis pm2 et hop!

un TRES sincère merci  pour ton aide, ta dispo et ton temps !
