### ISSUE TITLE
MP3 d'IBM

### ISSUE THREAD

**Issue by jzarca01** [Aymkdn/assistant-notifier#2]
Hello,

J'ai testé sur postman ton endpoint, il génère bien un mp3 mais ce dernier est illisible

Pour la requête vers notifier.php avec le body suivant
```
{
	"d": {
		"voice":{
	      "source":"IBM@fr-FR_ReneeVoice",
	      "key":""
	    },
		"texte": "you used to call me on my cellphone, late night when you need my help"
	}
}
```

Il me sort bien ```https://assistant.kodono.info/public/text_1541665797.mp3``` mais ce dernier est illisible et n'a pas la taille attendue

**Comment by Aymkdn** [comment]
(pour info, les fichiers sont effacés au bout de 5 minutes)

Alors, en fait j'ai remarqué qu'on utilisait pas la même URL pour la WatsonPlatform. Moi j'utilisais celle de Sydney (car j'avais pas vu qu'on pouvait sélectionner Francfort). J'ai recréé un compte en choisissant Francfort cette fois, et visiblement la clé dépend du serveur choisi, expliquant pourquoi ça merde avec toi.

Donc c'est bon, j'ai modifié et maintenant ta clé fonctionnera. Je vais également rajouter dans la doc de bien sélectionner Francfort pour le serveur.

Merci
