### ISSUE TITLE
Action play

### ISSUE THREAD

**Issue by jzarca01** [Aymkdn/assistant-notifier#3]
Hello,

Ce serait possible que tu implémentes également une action ***play*** où on lui file uniquement une url audio en entrée ?

Merci d'avance ;)

**Comment by Aymkdn** [comment]
Ça peut être **action** où si on détecte que *text* commence par http alors on utilise cet URL directement. Ça te semble bien ?

**Comment by jzarca01** [comment]
Parfait ;)

**Comment by Aymkdn** [comment]
Voilà c'est en ligne. Je n'ai pas testé mais ça devrait le faire (même si je viens juste de me réveiller d'une petite sieste ^^) : https://github.com/Aymkdn/assistant-notifier/commit/7d2c704769635172a810b6dfa034ee41af308632
